fix release action

diff --git a/.github/workflows/release-sdk.yml b/.github/workflows/release-sdk.yml
--- a/.github/workflows/release-sdk.yml
+++ b/.github/workflows/release-sdk.yml
@@ -154,7 +154,16 @@ jobs:
             rustc --version &&
             cargo --version &&
             apt-get update &&
-            apt-get install -y libssl-dev pkg-config
+            if command -v apt-get >/dev/null 2>&1; then
+              apt-get update && apt-get install -y libssl-dev pkg-config
+            elif command -v yum >/dev/null 2>&1; then
+              yum update -y && yum install -y openssl-devel pkgconfig
+            elif command -v apk >/dev/null 2>&1; then
+              apk add --no-cache openssl-dev pkgconfig
+            else
+              echo "Unable to install packages. No supported package manager found."
+              exit 1
+            fi
           CIBW_ENVIRONMENT_LINUX:
             PATH=$PATH:/usr/local/go/bin:/root/.cargo/bin
 
